kumuluzee:
  name: product-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ProductDS
      connection-url: jdbc:postgresql://localhost:5432/product
      username: dbuser
      password: postgres
      max-pool-size: 1
rest-properties:
  maintenance-mode: false
  broken: false